# 配置端口
server:
  port: 9090
  tomcat:
    uri-encoding: utf-8

# Security auth
auth:
  host:
    cors: http://localhost:8080,http://127.0.0.1:8080
  api:
    verify: /api/auth/verify
    free: /api/auth/login,/api/auth/verify,/api/test/**,/api/file/**,/api/sysUser/**
    user: /api/resource/user/**
    admin: /api/resource/admin/**

spring:
  # MySQL 数据库
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.20:3306/test_db?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    # 阿里连接池配置
    druid:
      initial-size: 5
      max-active: 30
      min-idle: 5
      max-wait: 10000
      # SQL防火墙
      filters: stat, wall
      # 配置监控选项，访问路径：http://localhost:9090/druid/
      web-stat-filter.enabled: true
      stat-view-servlet.enabled: true
      stat-view-servlet.login-username: admin
      stat-view-servlet.login-password: admin
  # Redis 缓存
  redis:
    host: 192.168.0.20
    port: 6379
    password: 123456
    timeout: 1800000
    lettuce:
      pool:
        max-idle: 8
        max-active: 8
        max-wait: -1ms
        min-idle: 0
      shutdown-timeout: 100ms
  # 邮件配置
  mail:
    host: smtp.163.com
    username: great__jin@163.com
    password: xxxxxxx
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
          starttls.required: true

# 绑定 MyBatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: xyz.ibudai.entity
  # 控制台打印 sql 语句
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
